config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :todos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :notes, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  protected
		def confirmation_required?
		  true
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        # flash[:success] = 'Todo was successfully created.'
        format.html { redirect_to @todo }
        format.json { render :show, status: :created, location: @todo }
      else
        flash[:danger] = 'There was a problem creating the Todo.'
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
         flash[:success] = 'Todo was successfully updated.'
        format.html { redirect_to @todo}
        format.json { render :show, status: :ok, location: @todo }
      else
         flash[:danger] = 'There was a problem updating the Todo.'
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      flash[:success] = 'Todo was successfully destroyed.'
      format.html { redirect_to todos_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demobootstrap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="img">
    <%= render 'shared/navigation' %>

    <%= yield %>

  </body>
  <%= render 'shared/footer' %>
</html>

app/views/shared/_footer.html.erb
<!-- <footer class="footer">
        <div class="container">
            <div class="row ">
                <div class="col-md-4 text-center text-md-left ">

                    <div class="py-0">
                        <h3 class="my-4 text-white">About<span class="mx-2 font-italic text-warning ">Eduonix</span></h3>

                        <p class="footer-links font-weight-bold">
                            <a class="text-white" href="#">Home</a>
                            |
                            <a class="text-white" href="#">Blog</a>
                            |
                            <a class="text-white" href="#">About</a>
                            |
                            <a class="text-white" href="#">Contact</a>
                        </p>
                        <p class="text-light py-4 mb-4">&copy;2019 Eduonix Learning Solutions Pvt. Ltd.</p>
                    </div>
                </div>

                <div class="col-md-4 text-white text-center text-md-left ">
                    <div class="py-2 my-4">
                        <div>
                            <p class="text-white"> <i class="fa fa-map-marker mx-2 "></i>
                                    309 - Rupa Solitaire,
                                   Bldg. No. A - 1, Sector - 1
                                  Mahape, Navi Mumbai - 400710</p>
                        </div>

                        <div>
                            <p><i class="fa fa-phone  mx-2 "></i> +91 22-27782183</p>
                        </div>
                        <div>
                            <p><i class="fa fa-envelope  mx-2"></i><a href="mailto:support@eduonix.com">support@eduonix.com</a></p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 text-white my-4 text-center text-md-left ">
                    <span class=" font-weight-bold ">About the Company</span>
					<p class="text-warning my-2" >We offer training and skill building courses across Technology, Design, Management, Science and Humanities.</p>
                    <div class="py-2">
                        <a href="#"><i class="fab fa-facebook fa-2x text-primary mx-3"></i></a>
                        <a href="#"><i class="fab fa-google-plus fa-2x text-danger mx-3"></i></a>
                        <a href="#"><i class="fab fa-twitter fa-2x text-info mx-3"></i></a>
                        <a href="#"><i class="fab fa-youtube fa-2x text-danger mx-3"></i></a>
                    </div>
                </div>
            </div>
        </div>
     </footer> -->

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Demo Bootstrap</a>
    </div>
      <ul class="nav navbar-nav navbar-right nav-item">
         <% if current_user %>
        <li class="nav-item">
          <%= link_to "Todos", todos_path %> </li>
        <li class="normal">
        <h5><%= current_user.email %></h5>
        </li>
        <% end %>
        <li class="dropdown">
          <%if current_user  %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Edit/Logout <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            <li class="divider"></li>
            <li><%= link_to   'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
          </ul>

      <% else %>

          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login/Signup <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
          </ul>
        </li>
      </ul>
      <% end %>
  </div>
</nav>

app/views/todos/_form.html.erb
<%= form_with(model: todo, html:{class: 'form-horizontal'},local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_field :title, required: true, placeholder: "Enter your Title", class: "textfield form-control" %>
    </div>
  </div>


  <div class="field form-group">
    <%= form.label :notes, class:'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_area :notes, required: true, placeholder: "Enter your text", class: "textfield form-control" %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class:"submit btn btn-primary"  %>
    </div>
  </div>
<% end %>

app/views/todos/edit.html.erb
<div class="col-xs-4" style="margin-top:80px">

</div>
<div class="col-xs-4" style="margin-top:80px">

  <h1>Editing Todo</h1>

  <%= render 'form', todo: @todo %>

  <%= link_to 'Show', @todo %> |
  <%= link_to 'Back', todos_path %>
</div>

app/views/todos/index.html.erb
<div class="col-xs-4" style="margin-top:80px">


</div>
<div class="col-xs-4" style="margin-top:80px">
  <ul class="nav nav-tabs" role="tablist">
    <li class="active"><%= link_to 'View list', todos_path %></li>
    <li><%= link_to 'New todo', new_todo_path %></li>
  </ul>

  <div class="text">
    <h3>Todos</h3>
  </div>
  <table class="table">
    <thead>

      <tr>
        <th>Title</th>
        <th>Notes</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @todos.each do |todo| %>
      <tr>
        <td>
          <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{todo.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{todo.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
            <%= todo.title %>
          </span>
          
        </td>
        <% if todo.notes? %>
        <!-- Button trigger modal -->
        <td><button class="btn btn-link" data-toggle="modal" data-target="#todo-<%= todo.id %>-notes">
          View notes
        </button></td>
        <!-- Modal -->
        <div class="modal fade" id="todo-<%= todo.id %>-notes" tabindex="-1" role="dialog" aria-labelledby="todo-<%= todo.id %>-label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title" id="todo-<%= todo.id %>-label"> Notes</h4>
              </div>
              <div class="modal-body">
                <%= todo.notes %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <% end %>


          <td><%= link_to 'Show', todo, class:'btn showbutton btn-xs' %></td>
          <td><%= link_to 'Edit', edit_todo_path(todo), class:'btn btn-info btn-xs' %></td>
          <td><%= link_to 'Delete', todo, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger deletebutton btn-xs'  %></td>

      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to new_todo_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Todo
  <% end %>
</div>

app/views/todos/new.html.erb
<div class="col-xs-4" style="margin-top:80px">
  
</div>
<div class="col-xs-4" style="margin-top:80px">

  <ul class="nav nav-tabs" role="tablist">
    <li><%= link_to 'View list', todos_path %></li>
    <li class="active"><%= link_to 'New todo', new_todo_path %></li>
  </ul>
  <div class="text">
    <h3>New Todo</h3>
  </div>
  <%= render 'form', todo: @todo %>

  <%= link_to 'Back', todos_path %>
</div>

app/views/todos/show.html.erb
<div class="col-xs-4" style="margin-top:80px">

</div>
<div class="col-xs-4" style="margin-top:80px">

  

  <p>
    <strong>Title:</strong>
    <%= @todo.title %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @todo.notes %>
  </p>

  <%= link_to 'Edit', edit_todo_path(@todo) %> |
  <%= link_to 'Back', todos_path %>

</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="todo-<%= @todo.id %>-label" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="todo-<%= @todo.id %>-label"> Notes</h4>
      </div>
      <div class="modal-body">
      <h5>Todo successfully created</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(window).on('load',function(){
        $('#myModal').modal('show');
    });
</script>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="col-xs-12">

</div>
<div class="col-xs-12 welcome">

</div>

    <div class="col-xs-12 imgcontainer ">

      <h1><i><b><u>Welcome to Todos Project</u></b></i></h1>

    </div>